In [292]:
2+2

4

In [293]:
import cv2

In [294]:
pwd

'/Users/austinmccarson'

In [295]:
imagename = '20190826_143318.jpg'
im = cv2.imread(imagename)

In [296]:
cv2.imwrite('foo.jpg', im)

True

In [297]:
type(im)

numpy.ndarray

In [298]:
im.shape

(3068, 2301, 3)

In [299]:
im[300,271,1]

223

In [300]:
type(im[300,271,1])

numpy.uint8

In [301]:
im.dtype

dtype('uint8')

# Slicing
start:stop:step
any of these can be omitted
:stop: means start to the end
: means all

In [302]:
#cv2.imwrite('foo.jpg', im[0:1000,:,:])

In [303]:
#im[:,:,1] = 0
#cv2.imwrite('foo.jpg', im)

In [304]:
#im[:,:,[0,1]] = 0
#cv2.imwrite('foo.jpg', im)

In [305]:
# lets turn one layer off using broadcasting
#im = cv2.imread(imagename)
#im[:,:,[1,2]] = 0 # leaving only the third layer
#cv2.imwrite('foo.jpg', im)

In [306]:
import numpy as np

In [307]:
a = np.random.randint(0,10,(5,4))

In [308]:
a>5

array([[False,  True,  True, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False,  True]])

In [309]:
a[ a>5 ] = -1

In [310]:
a[ isgreen ] = b[ isgreen ]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 3068

In [311]:
#cv2.imwrite('foo.jpg', im.sum(axis=2)/3 )

In [312]:
im.sum(axis=2).shape

(3068, 2301)

In [313]:
type(im.sum(axis=2))

numpy.ndarray

In [314]:
b = np.random.randint(0,10,(3,4,2))

In [315]:
b.sum(axis=2)

array([[ 9,  8, 13, 10],
       [ 8, 14,  6,  9],
       [10,  9, 11,  7]])

In [316]:
im = cv2.imread(imagename)
isgreen = im[:,:,1]/im.sum(axis=2) > .4
isgreen

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [317]:
isgreen.sum()

3486377

In [318]:
otherimagename = 'cactus.jpg'
otherim = cv2.imread(otherimagename)

In [319]:
im[ isgreen ] = otherim[ isgreen ]

In [320]:
cv2.imwrite('foo.jpg', im)

True